### ISSUE TITLE
In the Footer's Links, Author Names are Incorrectly Spaced.

### ISSUE THREAD

**Issue by dylan-k** [WaltersArtMuseum/journal-thewalters-org#22]
For example on a page like this one https://journal.thewalters.org/volume/75/note/reading-and-displaying-monograms-on-byzantine-signet-rings/ 

at the bottom where another article is mentioned, the list of author names doesn't use the oxford comma functions added with #14

**Comment by dylan-k** [comment]
Issue #14 did address some of this, but not completely. There were incorrect spaces/oxford-commas in some of the author lists.
 
We still see some errors in the footer. At the end of most articles, there's a link to the "next" article, including the authors of the linked article. We need to apply the same fix there.

Here are some pages where this can occur:

**footer links to article with one author:**
https://journal.thewalters.org/volume/75/note/meek-and-sitting-upon-an-ass-a-newly-acquired-medieval-palmesel/

**footer links to article with two authors:** 
https://journal.thewalters.org/volume/75/note/reading-and-displaying-monograms-on-byzantine-signet-rings/

**footer links to article with multiple authors:**
https://journal.thewalters.org/volume/74/note/new-acquisition-boldinis-lady-with-a-guitar/ 

And here are some screenshots of how the author lists are supposed to look.

<img width="447" alt="2022-12-21 10_52_46-“Meek and Sitting upon an Ass”_ A Newly Acquired Medieval Palmesel _ The Journal" src="https://user-images.githubusercontent.com/2204716/208948317-ed805ee6-79ba-4282-b272-7e2d0f723f95.png">

<img width="412" alt="2022-12-21 10_53_20-" src="https://user-images.githubusercontent.com/2204716/208948347-be344402-6e8b-4f40-b674-91ae24f81b7e.png">

<img width="536" alt="2022-12-21 10_52_22-Giovanni Boldini’s Lady with a Guitar _ The Journal of the Walters Art Museum" src="https://user-images.githubusercontent.com/2204716/208948392-5c0faed7-588c-458b-a4a7-161e41e2ad18.png">

@rbowler-wam could you please take a moment to check each of the examples linked above, and can you confirm that you also see the lists correctly formatted? There should be a correct oxford comma, and no double spacing.

**Comment by rbowler-wam** [comment]
@dylan-k 
Looks like it is working well in new and previously published content. Confirming formatting is correct. 

<im
<img width="1017" alt="Screenshot 2022-12-21 at 12 11 54 PM" src="https://user-images.githubusercontent.com/47460821/208964303-cb907293-abcd-4ef7-a227-ee784d0c3344.png">
g width="765" alt="Screenshot 2022-12-21 at 12 10 30 PM" src="https://user-images.githubusercontent.com/47460821/208964058-7db45085-6549-4a0c-801a-7869211b7314.png">

**Comment by rbowler-wam** [comment]
@dylan-k 
Sorry about the header images. I was checking both. Footers also look good. 

<img width="785" alt="Screenshot 2022-12-21 at 12 16 18 PM" src="https://user-images.githubusercontent.com/47460821/208965125-2b1f2775-4584-43e6-b7c5-981d878b1f1e.png">
