### ISSUE TITLE
Test removing rocket-loader cached path to see if Analytics Works

### ISSUE THREAD

**Issue by theandystratton** [WaltersArtMuseum/journal-thewalters-org#36]
When loading site, in console, we see:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/46582227/230955951-93f95edf-7dcc-4581-bc8a-a84b506aac69.png">

This seems to breaking Google Tag Manager, related to #33

**Comment by dylan-k** [comment]
This could also be the cause of #32

**Comment by theandystratton** [comment]
(Please re-open if you're not seeing anything in Google Analytics within the next few days!)
